<a href="https://colab.research.google.com/github/drawcodeboy/Colab_Test/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Numpy
#scikit-learn, 사이킷런 = 머신러닝을 대표하는 파이썬 라이브러리
import numpy as np
from sklearn import preprocessing

In [6]:
#Numpy를 이용한 input_data 형성
input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])
print('Input data:', input_data, sep = '\n')

Input data:
[[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]


In [5]:
#Binarization, 이진화
#threshold를 기준으로 데이터를 이진화 시킨다.
data_binarized = preprocessing.Binarizer(threshold = 2.1).transform(input_data)
print('Binarized data:', data_binarized, sep = '\n')

Binarized data:
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [11]:
#Mean Removal, 평균 제거

print("Before:")
print("Mean =", input_data.mean(axis = 0))
print("Std deviation =", input_data.std(axis = 0))

data_scaled = preprocessing.scale(input_data)
print("\nAfter:")
print("Mean =", data_scaled.mean(axis = 0))
print("Std deviation =", data_scaled.std(axis = 0))

Before:
Mean = [ 1.83333333  0.16666667  2.13333333 -2.36666667]
Std deviation = [3.42669261 5.75634915 1.42906341 7.18207646]

After:
Mean = [ 0.42739717 -0.45674468  0.37351416 -0.34416666]
Std deviation = [0.57453827 1.32774466 0.33810537 1.06931618]


In [12]:
#Scaling, 스케일링

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range = (0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print('Min max scaled data:', data_scaled_minmax, sep = '\n')

Min max scaled data:
[[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


In [13]:
#Normalization, 정규화

data_normalized_l1 = preprocessing.normalize(input_data, norm = 'l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm = 'l2')
print('L1 normalzied data:', data_normalized_l1, sep = '\n')
print('L1 normalzied data:', data_normalized_l1, sep = '\n')

L1 normalzied data:
[[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]
L1 normalzied data:
[[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]
