<a href="https://colab.research.google.com/github/drawcodeboy/Colab_Test/blob/main/np_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://bskyvision.com/748
# https://banmans.tistory.com/32

In [ ]:
# numpy import 
import numpy as np

In [ ]:
# numpy array declaration

# 1. list -> numpy array로 변환
li = list([1, 2, 3])
arr = np.array(li)
print(arr)

# 2.
arr2 = np.array([1, 2, 3])
print(arr2)

[1 2 3]
[1 2 3]


In [ ]:
# arange

# Python의 range처럼 사용가능, 배열 선언할 때 용이함. 다차원은 어떻게 하는지 모르겠음
# ascending, descending, 증감 값까지 설정해서 사용할 수 있음

arr = np.arange(10)
print(arr)

arr2 = np.arange(1, 10)
print(arr2)

arr3 = np.arange(10, 0, -1)
print(arr3)

arr4 = np.arange(1, 5.5, 0.5)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
import numpy as np #해당 셀부터 np가 선언되지 않았다고 오류 떠서 재선언함

# shape

# 배열의 형태를 알려주는 method
# (3, ) = 3 col 크기의 vector, (3, 4) = 3 row 4 col 크기의 matrix, (3, 2, 2) = tensor(?)

arr = np.arange(1, 4)
print(arr.shape)

arr2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(arr2.shape)

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3.shape)

(3,)
(3, 4)
(3, 2, 2)


In [ ]:
# reshape

# Numpy의 배열의 모양을 바꿀 때는 reshape 메서드 사용
# 바뀐 배열을 return하기 때문에 새로운 변수를 declare해야 함

# 값의 개수가 맞지 않는 상태로 reshape 할 경우 ValueError가 난다.
# resize 메서드를 통해 가능 (하단 셀 참조)

arr = np.arange(1, 11)
print(arr)

arr2 = arr.reshape(2, 5)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# resize
# 배열의 모양과 사이즈 바꾸기

# Numpy의 모양 뿐만 아니라 사이즈까지 바꿀 수 있다. => resize 메서드 사용

arr = np.arange(1, 11)
print(arr)

arr.resize(2, 4)
print(arr)

arr.resize(3, 5)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5]
 [6 7 8 0 0]
 [0 0 0 0 0]]


In [ ]:
# max

# 원소들 중 최댓값을 반환

arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(arr.max())

11


In [34]:
# argmax

# 원소들 중 최댓값을 갖는 index 반환
# 다차원 array일 경우, ~row, ~col 이런식이 아닌 첫 원소부터 하나씩 count하여 몇 번째 index인지를 반환한다.

arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(arr.argmax())

11


In [ ]:
# min, argmin 또한 존재

In [ ]:
# sort

# 배열의 원소를 정렬

arr = np.arange(10, 0, -1)
arr.sort()
print(arr)

# 각 vector로 정렬됨
arr2 = np.array([[3, 6, 1, -1], [2, -9, 1, 5], [6, -10, 4, 5]])
arr2.sort()
print(arr2)

# argsort
# 정렬 이후 각 원소의 인덱스가 원래 무엇이었는지

[ 1  2  3  4  5  6  7  8  9 10]
[[ -1   1   3   6]
 [ -9   1   2   5]
 [-10   4   5   6]]


In [ ]:
# astype
# 배열을 복사한 다음 자료형을 바꿔줌

arr = np.arange(1, 11)
arr_float = arr.astype(float)
print(arr_float)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# mean, var, std, sum
# 평균, 분산, 표준편차, 합(배열 원소들)

arr = np.arange(1, 11)

print(arr.mean(), arr.var(), arr.std(), arr.sum(), sep = ' | ')

5.5 | 8.25 | 2.8722813232690143 | 55
